import { useEffect, useMemo, useState } from 'react';
import { Archive, Check, Circle, ClipboardList, Command, Download, FileText, FolderKanban, Moon, Plus, Search, Settings, Sparkles, Sun, Target, Trash2, Upload, Users } from 'lucide-react';

type View='Dashboard'|'Projects'|'Notes'|'Tasks'|'Decisions'|'Weekly'|'Activity'|'Settings';
type Role='CEO'|'CTO'|'CTPO'|'CGO';
type Priority='Low'|'Medium'|'High';
type ProjectStatus='Idea'|'Active'|'Paused'|'Completed';
type TaskStatus='Todo'|'In Progress'|'Done';
type Project={id:string;name:string;description:string;status:ProjectStatus;priority:Priority;owner:string};
type Note={id:string;projectId:string;title:string;content:string};
type Task={id:string;projectId:string;title:string;description:string;status:TaskStatus;priority:Priority;assignedTo?:string};
type Decision={id:string;projectId:string;title:string;decision:string;consequences:string};
type Weekly={id:string;projectId:string;title:string;done:boolean};
type Member={id:string;name:string;email:string;role:Role};
type Activity={id:string;entity_type:string;action:string;created_at:string;name?:string;email?:string;metadata?:Record<string,unknown>};
type Store={projects:Project[];notes:Note[];tasks:Task[];decisions:Decision[];weekly:Weekly[]};

const KEY='launchx-project-os:frontend-v3';
const TOKEN_KEY='launchx-project-os:api-token';
const API_KEY='launchx-project-os:api-base';
const defaultApi=import.meta.env.VITE_API_BASE_URL||'https://api.launchx.in';
const uid=()=>crypto.randomUUID();
const seed:Store={projects:[{id:'p1',name:'LaunchX Project OS',description:'Shared CXO workspace for execution.',status:'Active',priority:'High',owner:'CEO'}],notes:[{id:'n1',projectId:'p1',title:'Product thesis',content:'## Server-backed Project OS\nCEO creates workspace. CTO, CTPO and CGO contribute.'}],tasks:[{id:'t1',projectId:'p1',title:'Validate collaboration flow',description:'Login from another browser and confirm shared data.',status:'Todo',priority:'High'}],decisions:[{id:'d1',projectId:'p1',title:'ADR-001: CEO-owned workspace',decision:'CEO owns workspace bootstrap and destructive sync.',consequences:'Team can contribute without overwriting source of truth.'}],weekly:[{id:'w1',projectId:'p1',title:'Ship stable collaboration v1',done:false}]};
function load():Store{try{return JSON.parse(localStorage.getItem(KEY)||'') as Store}catch{return seed}}
function badge(v:string){return 'badge '+String(v||'').toLowerCase().replaceAll(' ','-')}
function projectName(data:Store,id?:string){return data.projects.find(p=>p.id===id)?.name||'No project'}
function memberName(ms:Member[],id?:string){return ms.find(m=>m.id===id)?.name||'Unassigned'}
function md(v:string){return v.replaceAll('&','&amp;').replaceAll('<','&lt;').replace(/^## (.*)$/gm,'<h2>$1</h2>').replace(/^# (.*)$/gm,'<h1>$1</h1>').replace(/^- (.*)$/gm,'<li>$1</li>').replace(/\n/g,'<br/>')}
function fromWorkspace(w:any):Store{return{projects:(w.projects||[]).map((p:any)=>({id:p.id,name:p.name,description:p.description||'',status:p.status,priority:p.priority,owner:p.owner_user_id?'Team':'CEO'})),notes:(w.notes||[]).map((n:any)=>({id:n.id,projectId:n.project_id||'',title:n.title,content:n.content||''})),tasks:(w.tasks||[]).map((t:any)=>({id:t.id,projectId:t.project_id||'',title:t.title,description:t.description||'',status:t.status,priority:t.priority,assignedTo:t.assigned_to||undefined})),decisions:(w.decisions||[]).map((d:any)=>({id:d.id,projectId:d.project_id||'',title:d.title,decision:d.decision||'',consequences:d.consequences||''})),weekly:(w.weekly||[]).map((x:any)=>({id:x.id,projectId:x.project_id||'',title:x.title,done:Boolean(x.done)}))}}

export default function App(){
 const[data,setData]=useState<Store>(load);const[view,setView]=useState<View>('Dashboard');const[dark,setDark]=useState(()=>localStorage.getItem('theme')!=='light');const[projectId,setProjectId]=useState(()=>data.projects[0]?.id||'');const[query,setQuery]=useState('');const[cmd,setCmd]=useState(false);const[apiBase,setApiBase]=useState(()=>localStorage.getItem(API_KEY)||defaultApi);const[token,setToken]=useState(()=>localStorage.getItem(TOKEN_KEY)||'');const[email,setEmail]=useState('ajit@theajit.in');const[password,setPassword]=useState('');const[userRole,setUserRole]=useState<Role|null>(null);const[syncStatus,setSyncStatus]=useState(()=>token?'Connected':'Local only');const[members,setMembers]=useState<Member[]>([]);const[activity,setActivity]=useState<Activity[]>([]);const[newMember,setNewMember]=useState({name:'',email:'',password:'',role:'CTO' as Exclude<Role,'CEO'>});const connected=Boolean(token);const isCEO=userRole==='CEO';
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(data)),[data]);useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('theme',dark?'dark':'light')},[dark]);useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCmd(true)}if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;if(e.key==='Escape')setCmd(false);if(e.key.toLowerCase()==='p')void addProject();if(e.key.toLowerCase()==='n')void addNote();if(e.key.toLowerCase()==='t')void addTask('Todo')};addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)});
 useEffect(()=>{if(!token)return;void refreshWorkspace();const id=setInterval(()=>void refreshWorkspace(false),30000);return()=>clearInterval(id)},[token]);
 const stats=useMemo(()=>[{label:'Projects',value:data.projects.length,detail:`${data.projects.filter(p=>p.status==='Active').length} active`,icon:<FolderKanban/>},{label:'Open tasks',value:data.tasks.filter(t=>t.status!=='Done').length,detail:`${data.tasks.filter(t=>t.priority==='High').length} high priority`,icon:<ClipboardList/>},{label:'ADRs',value:data.decisions.length,detail:'decision log',icon:<Archive/>},{label:'Weekly',value:`${data.weekly.filter(w=>w.done).length}/${data.weekly.length}`,detail:'focus closed',icon:<Target/>}], [data]);
 async function api(path:string,body?:unknown,auth=true,method?:string){const res=await fetch(`${apiBase.replace(/\/$/,'')}${path}`,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...(auth&&token?{Authorization:`Bearer ${token}`}:{})},body:body?JSON.stringify(body):undefined});const json=await res.json();if(!res.ok)throw new Error(json.message||json.error||'API request failed');return json}
 async function refreshWorkspace(show=true,nextToken=token){if(!nextToken)return;try{const base=apiBase.replace(/\/$/,'');const [meRes,wsRes,actRes]=await Promise.all([fetch(`${base}/me`,{headers:{Authorization:`Bearer ${nextToken}`}}),fetch(`${base}/workspace`,{headers:{Authorization:`Bearer ${nextToken}`}}),fetch(`${base}/activity`,{headers:{Authorization:`Bearer ${nextToken}`}})]);const me=await meRes.json();const ws=await wsRes.json();const act=await actRes.json();if(!wsRes.ok)throw new Error(ws.message||'Could not load workspace');const next=fromWorkspace(ws);setData(next);setMembers(ws.members||[]);setActivity(Array.isArray(act)?act:[]);setUserRole(me.role||null);if(!next.projects.find(p=>p.id===projectId))setProjectId(next.projects[0]?.id||'');if(show)setSyncStatus(`Auto-synced ${new Date().toLocaleTimeString()}`)}catch(e){setSyncStatus(e instanceof Error?e.message:'Sync failed')}}
 async function login(){try{setSyncStatus('Logging in...');const json=await api('/auth/login',{email,password},false);setToken(json.token);setUserRole(json.user.role);localStorage.setItem(TOKEN_KEY,json.token);localStorage.setItem(API_KEY,apiBase);await refreshWorkspace(true,json.token)}catch(e){setSyncStatus(e instanceof Error?e.message:'Login failed')}}
 async function bootstrap(){try{setSyncStatus('Creating CEO workspace...');const json=await api('/auth/bootstrap',{organizationName:'LaunchX',name:'Ajit Satpathy',email,password,role:'CEO'},false);setToken(json.token);setUserRole('CEO');localStorage.setItem(TOKEN_KEY,json.token);localStorage.setItem(API_KEY,apiBase);await refreshWorkspace(true,json.token)}catch(e){setSyncStatus(e instanceof Error?e.message:'Workspace creation failed')}}
 function logout(){setToken('');setUserRole(null);setMembers([]);setActivity([]);localStorage.removeItem(TOKEN_KEY);setSyncStatus('Signed out. Local workspace remains available.')}
 async function createMember(){try{if(!isCEO){setSyncStatus('Only CEO can create team members.');return}setSyncStatus('Creating team member...');await api('/team/members',newMember);setNewMember({name:'',email:'',password:'',role:'CTO'});await refreshWorkspace();setSyncStatus('Team member created. Share credentials securely.')}catch(e){setSyncStatus(e instanceof Error?e.message:'Could not create member')}}
 async function pushLocalData(){try{if(!isCEO){setSyncStatus('Only CEO can replace server data.');return}setSyncStatus('Replacing server workspace from local data...');await api('/workspace/import',{...data,replace:true});await refreshWorkspace()}catch(e){setSyncStatus(e instanceof Error?e.message:'Sync failed')}}
 async function mutate(path:string,body:any,local:()=>void,method?:string){try{if(token){await api(path,body,true,method);await refreshWorkspace();return}local()}catch(e){setSyncStatus(e instanceof Error?e.message:'Save failed');local()}}
 async function remove(path:string,local:()=>void){try{if(token){await api(path,undefined,true,'DELETE');await refreshWorkspace();return}local()}catch(e){setSyncStatus(e instanceof Error?e.message:'Delete failed')}}
 async function addProject(){const item:Project={id:uid(),name:'New project',description:'Define the execution thesis.',status:'Idea',priority:'Medium',owner:'CEO'};await mutate('/projects',{name:item.name,description:item.description,status:item.status,priority:item.priority},()=>setData(d=>({...d,projects:[item,...d.projects]})));setView('Projects')}
 async function deleteProject(id:string){await remove(`/projects/${id}`,()=>setData(d=>({...d,projects:d.projects.filter(x=>x.id!==id)})))}
 async function addNote(){const item:Note={id:uid(),projectId,title:'Untitled note',content:'## New note\nWrite in markdown.'};await mutate('/notes',{projectId:token?projectId:null,title:item.title,content:item.content},()=>setData(d=>({...d,notes:[item,...d.notes]})));setView('Notes')}
 async function deleteNote(id:string){await remove(`/notes/${id}`,()=>setData(d=>({...d,notes:d.notes.filter(x=>x.id!==id)})))}
 async function addTask(status:TaskStatus){const assignee=members.find(m=>m.role==='CTO')?.id;const item:Task={id:uid(),projectId,title:'New task',description:'Define the next action.',status,priority:'Medium',assignedTo:assignee};await mutate('/tasks',{projectId:token?projectId:null,title:item.title,description:item.description,status:item.status,priority:item.priority,assignedTo:assignee||null},()=>setData(d=>({...d,tasks:[item,...d.tasks]})));setView('Tasks')}
 async function assignTask(id:string,assignedTo:string){const t=data.tasks.find(x=>x.id===id);if(!t)return;await mutate(`/tasks/${id}`,{assignedTo:assignedTo||null},()=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,assignedTo}:x)})),'PATCH')}
 async function moveTask(id:string,status:TaskStatus){await mutate(`/tasks/${id}`,{status},()=>setData(d=>({...d,tasks:d.tasks.map(x=>x.id===id?{...x,status}:x)})),'PATCH')}
 async function deleteTask(id:string){await remove(`/tasks/${id}`,()=>setData(d=>({...d,tasks:d.tasks.filter(x=>x.id!==id)})))}
 async function addDecision(){const item:Decision={id:uid(),projectId,title:'ADR: New decision',decision:'Decision',consequences:'Expected impact'};await mutate('/decisions',{projectId:token?projectId:null,title:item.title,decision:item.decision,consequences:item.consequences},()=>setData(d=>({...d,decisions:[item,...d.decisions]})));setView('Decisions')}
 async function deleteDecision(id:string){await remove(`/decisions/${id}`,()=>setData(d=>({...d,decisions:d.decisions.filter(x=>x.id!==id)})))}
 async function addWeekly(){const item:Weekly={id:uid(),projectId,title:'New weekly priority',done:false};await mutate('/weekly-priorities',{projectId:token?projectId:null,title:item.title,done:false},()=>setData(d=>({...d,weekly:[item,...d.weekly]})));setView('Weekly')}
 async function toggleWeekly(id:string){const item=data.weekly.find(w=>w.id===id);if(!item)return;const done=!item.done;await mutate(`/weekly-priorities/${id}`,{done},()=>setData(d=>({...d,weekly:d.weekly.map(w=>w.id===id?{...w,done}:w)})),'PATCH')}
 async function deleteWeekly(id:string){await remove(`/weekly-priorities/${id}`,()=>setData(d=>({...d,weekly:d.weekly.filter(x=>x.id!==id)})))}
 function exportJson(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='launchx-project-os.json';a.click()}function importJson(file?:File){if(!file)return;const r=new FileReader();r.onload=()=>setData(JSON.parse(String(r.result)));r.readAsText(file)}function resetSamples(){if(confirm('Reset local sample data? This will not delete server data.'))setData(seed)}
 const actions=[['New project',addProject],['New note',addNote],['New task',()=>addTask('Todo')],['New ADR',addDecision],['New weekly priority',addWeekly],['Refresh server workspace',()=>refreshWorkspace()]] as const;const addForView=()=>view==='Notes'?addNote():view==='Tasks'?addTask('Todo'):view==='Decisions'?addDecision():view==='Weekly'?addWeekly():addProject();
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">LX</div><div><b>LaunchX</b><span>Project OS</span></div></div><Nav view={view} setView={setView}/><button className="command-hint" onClick={()=>setCmd(true)}><Command size={15}/> Ctrl K</button></aside><main><header className="topbar"><div><p className="eyebrow">{connected?`${userRole||'Team'} · auto-sync on`:'Local-first mode'}</p><h1>{view}</h1><p className="subhead">{syncStatus}</p></div><div className="top-actions"><select value={projectId} onChange={e=>setProjectId(e.target.value)}>{data.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="ghost" onClick={()=>setCmd(true)}><Search size={16}/> Command</button><button className="square" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="primary" onClick={()=>void addForView()}><Plus/> Add</button></div></header>
 {view==='Dashboard'&&<section className="dashboard"><div className="hero card"><span className="pill"><Sparkles size={14}/> Collaboration-safe v1</span><h2>CEO owns the workspace. CXOs contribute.</h2><p>Auto-sync, audit logs, project-linked ADRs, assignments and deletes are now visible.</p></div>{stats.map(s=><div className="stat card" key={s.label}>{s.icon}<span>{s.label}</span><strong>{s.value}</strong><small>{s.detail}</small></div>)}<Panel title="This week">{data.weekly.map(w=><Row key={w.id} title={w.title} meta={projectName(data,w.projectId)} done={w.done} onToggle={()=>void toggleWeekly(w.id)} onDelete={()=>void deleteWeekly(w.id)}/>)}</Panel><Panel title="Recent Activity">{activity.slice(0,5).map(a=><button className="list-card" key={a.id}><b>{a.name||a.email||'Team'} {a.action} {a.entity_type}</b><span>{new Date(a.created_at).toLocaleString()}</span></button>)}</Panel></section>}
 {view==='Projects'&&<section className="cards">{data.projects.map(p=><article className="entity-card" key={p.id}><div><h3>{p.name}</h3><p>{p.description}</p></div><div className="meta-row"><span className={badge(p.status)}>{p.status}</span><span className={badge(p.priority)}>{p.priority}</span><small>{p.owner}</small><button className="mini-danger" onClick={()=>void deleteProject(p.id)}><Trash2 size={14}/> Delete</button></div></article>)}</section>}
 {view==='Notes'&&<section><div className="searchbar"><label><Search size={16}/><input placeholder="Search notes" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary" onClick={()=>void addNote()}><Plus/> Note</button></div><div className="cards">{data.notes.filter(n=>(n.title+n.content).toLowerCase().includes(query.toLowerCase())).map(n=><article className="entity-card note-card" key={n.id}><h3>{n.title}</h3><div className="markdown compact" dangerouslySetInnerHTML={{__html:md(n.content)}}/><div className="meta-row"><small>{projectName(data,n.projectId)}</small><button className="mini-danger" onClick={()=>void deleteNote(n.id)}><Trash2 size={14}/> Delete</button></div></article>)}</div></section>}
 {view==='Tasks'&&<section className="board">{(['Todo','In Progress','Done'] as TaskStatus[]).map(status=><div className="column" key={status}><div className="column-head"><h3>{status}</h3><button onClick={()=>void addTask(status)}><Plus size={15}/></button></div>{data.tasks.filter(t=>t.status===status).map(t=><article className="task-card" key={t.id}><b>{t.title}</b><p>{t.description}</p><span className={badge(t.priority)}>{t.priority}</span><small>{projectName(data,t.projectId)}</small><select value={t.assignedTo||''} onChange={e=>void assignTask(t.id,e.target.value)}><option value="">Unassigned</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select><div className="settings-grid"><select value={t.status} onChange={e=>void moveTask(t.id,e.target.value as TaskStatus)}><option>Todo</option><option>In Progress</option><option>Done</option></select><button className="mini-danger" onClick={()=>void deleteTask(t.id)}><Trash2 size={14}/> Delete</button></div><small>Assigned: {memberName(members,t.assignedTo)}</small></article>)}</div>)}</section>}
 {view==='Decisions'&&<section className="timeline">{data.decisions.map(d=><article className="decision-card" key={d.id}><h3>{d.title}</h3><span className="badge active">{projectName(data,d.projectId)}</span><p><b>Decision:</b> {d.decision}</p><p><b>Impact:</b> {d.consequences}</p><button className="mini-danger" onClick={()=>void deleteDecision(d.id)}><Trash2 size={14}/> Delete</button></article>)}</section>}
 {view==='Weekly'&&<section className="weekly">{data.weekly.map(w=><Row key={w.id} title={w.title} meta={projectName(data,w.projectId)} done={w.done} onToggle={()=>void toggleWeekly(w.id)} onDelete={()=>void deleteWeekly(w.id)}/>)}</section>}
 {view==='Activity'&&<section className="timeline">{activity.map(a=><article className="decision-card" key={a.id}><h3>{a.entity_type} · {a.action}</h3><p>{a.name||a.email||'Team member'} at {new Date(a.created_at).toLocaleString()}</p></article>)}</section>}
 {view==='Settings'&&<SettingsView connected={connected} isCEO={isCEO} apiBase={apiBase} setApiBase={setApiBase} email={email} setEmail={setEmail} password={password} setPassword={setPassword} syncStatus={syncStatus} bootstrap={bootstrap} login={login} logout={logout} pushLocalData={pushLocalData} refreshWorkspace={refreshWorkspace} exportJson={exportJson} importJson={importJson} resetSamples={resetSamples} members={members} newMember={newMember} setNewMember={setNewMember} createMember={createMember}/>}</main><nav className="bottom-nav"><Nav view={view} setView={setView} compact/></nav>{cmd&&<div className="overlay" onClick={()=>setCmd(false)}><div className="palette" onClick={e=>e.stopPropagation()}><div className="palette-head"><Command/><input autoFocus placeholder="Type a command"/></div>{actions.map(([label,run])=><button key={label} onClick={()=>{void run();setCmd(false)}}>{label}</button>)}</div></div>}</div>}
function SettingsView(p:any){return <section className="settings settings-v2"><h2>Workspace Settings</h2><p>CEO creates workspace. CTO, CTPO and CGO contribute. Server replace is CEO-only.</p><div className="settings-section"><span className={p.connected?'badge active':'badge paused'}>{p.connected?'Connected':'Local only'}</span><h3>Account & Workspace</h3><input value={p.apiBase} onChange={(e:any)=>p.setApiBase(e.target.value)} placeholder="API URL"/>{!p.connected&&<><input value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)} placeholder="Email"/><input type="password" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)} placeholder="Password"/><div className="settings-grid"><button onClick={p.bootstrap}>Create CEO workspace</button><button onClick={p.login}>Login</button></div></>}{p.connected&&<div className="settings-grid"><button onClick={p.refreshWorkspace}>Refresh now</button><button className="ghost-button" onClick={p.logout}>Logout</button></div>}<p className="sync-status">{p.syncStatus}</p></div>{p.connected&&<div className="settings-section"><h3><Users size={18}/> Team Management</h3><p>Only CEO can create members. Others can contribute to execution data.</p>{p.isCEO&&<div className="editor-card"><input placeholder="Name" value={p.newMember.name} onChange={(e:any)=>p.setNewMember({...p.newMember,name:e.target.value})}/><input placeholder="Email" value={p.newMember.email} onChange={(e:any)=>p.setNewMember({...p.newMember,email:e.target.value})}/><input type="password" placeholder="Temporary password" value={p.newMember.password} onChange={(e:any)=>p.setNewMember({...p.newMember,password:e.target.value})}/><select value={p.newMember.role} onChange={(e:any)=>p.setNewMember({...p.newMember,role:e.target.value})}><option>CTO</option><option>CTPO</option><option>CGO</option></select><button onClick={p.createMember}>Create member</button></div>}<div className="team-list">{p.members.map((m:Member)=><div className="row" key={m.id}><span className={badge(m.role)}>{m.role}</span><button className="row-main"><b>{m.name}</b><span>{m.email}</span></button></div>)}</div></div>}<div className="settings-section"><h3>Backup & Restore</h3><div className="settings-grid"><button onClick={p.exportJson}><Download/> Export JSON</button><label className="button-like"><Upload/> Import JSON<input type="file" hidden accept="application/json" onChange={(e:any)=>p.importJson(e.target.files?.[0])}/></label></div></div>{p.isCEO&&<div className="settings-section danger-zone"><h3>CEO Danger Zone</h3><p>Replace server data with this browser’s local copy. Use only during recovery/migration.</p><button onClick={p.pushLocalData}>Replace server with local</button><button onClick={p.resetSamples}>Reset local sample data</button></div>}</section>}
function Nav({view,setView,compact}:{view:View;setView:(v:View)=>void;compact?:boolean}){const items=[['Dashboard',<Sparkles/>],['Projects',<FolderKanban/>],['Notes',<FileText/>],['Tasks',<ClipboardList/>],['Decisions',<Archive/>],['Weekly',<Target/>],['Activity',<Command/>],['Settings',<Settings/>]] as const;return <>{items.slice(0,compact?8:8).map(([v,icon])=><button key={v} className={view===v?'active':''} onClick={()=>setView(v as View)}>{icon}<span>{v}</span></button>)}</>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="card panel"><div className="panel-head"><h3>{title}</h3></div>{children}</section>}
function Row({title,meta,done,onToggle,onDelete}:{title:string;meta:string;done:boolean;onToggle:()=>void;onDelete:()=>void}){return <div className="row"><button className="check" onClick={onToggle}>{done?<Check/>:<Circle/>}</button><button className="row-main"><b>{title}</b><span>{meta}</span></button><button className="mini-danger" onClick={onDelete}><Trash2 size={14}/></button></div>}
